import type { AchievementTier, SeasonSummary } from "@/app/members/lib/memberProfile";
import type { PlayerAward } from "@/app/members/lib/playerAwards";
import type { GameDataLookup } from "@/lib/ndsc-data";

export type AchievementContext = {
  career: SeasonSummary;
  awards: PlayerAward[];
  records: GameDataLookup["byName"][string];
  bestHits: number;
  bestRuns: number;
  bestRbi: number;
  bestDefensiveOuts: number;
  mvpAwards: number;
  profileCompleteFields: number;
};

export type AchievementDefinition = {
  key: string;
  title: string;
  tier: AchievementTier;
  target: number;
  detail: string;
  progress: (context: AchievementContext) => number;
};

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    key: "first-hit",
    title: "First Hit",
    tier: "bronze",
    target: 1,
    detail: "Record your first NDSC hit.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "first-run",
    title: "First Run",
    tier: "bronze",
    target: 1,
    detail: "Cross the plate for the first time.",
    progress: ({ career }) => career.runs,
  },
  {
    key: "first-rbi",
    title: "First RBI",
    tier: "bronze",
    target: 1,
    detail: "Drive in your first run.",
    progress: ({ career }) => career.rbi,
  },
  {
    key: "profile-started",
    title: "Profile Started",
    tier: "bronze",
    target: 1,
    detail: "Add at least one profile detail.",
    progress: ({ profileCompleteFields }) => profileCompleteFields,
  },
  {
    key: "profile-complete",
    title: "Profile Complete",
    tier: "silver",
    target: 4,
    detail: "Set member since, position, bats and throws.",
    progress: ({ profileCompleteFields }) => profileCompleteFields,
  },
  {
    key: "multi-hit-game",
    title: "Multi-Hit Game",
    tier: "silver",
    target: 2,
    detail: "Two or more hits in one game.",
    progress: ({ bestHits }) => bestHits,
  },
  {
    key: "three-hit-game",
    title: "Three-Hit Game",
    tier: "gold",
    target: 3,
    detail: "Record three hits in one game.",
    progress: ({ bestHits }) => bestHits,
  },
  {
    key: "four-hit-game",
    title: "Four-Hit Game",
    tier: "platinum",
    target: 4,
    detail: "Record four hits in one game.",
    progress: ({ bestHits }) => bestHits,
  },
  {
    key: "25-career-hits",
    title: "25 Career Hits",
    tier: "silver",
    target: 25,
    detail: "Reach 25 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "25-career-runs",
    title: "25 Career Runs",
    tier: "silver",
    target: 25,
    detail: "Score 25 career runs.",
    progress: ({ career }) => career.runs,
  },
  {
    key: "25-career-rbi",
    title: "25 Career RBI",
    tier: "silver",
    target: 25,
    detail: "Record 25 career RBI.",
    progress: ({ career }) => career.rbi,
  },
  {
    key: "walk-watch",
    title: "Walk Watch",
    tier: "silver",
    target: 25,
    detail: "Draw 25 career walks.",
    progress: ({ career }) => career.walks,
  },
  {
    key: "patient-hitter",
    title: "Patient Hitter",
    tier: "gold",
    target: 50,
    detail: "Draw 50 career walks.",
    progress: ({ career }) => career.walks,
  },
  {
    key: "first-home-run",
    title: "First Home Run",
    tier: "silver",
    target: 1,
    detail: "Hit your first NDSC home run.",
    progress: ({ career }) => career.homeRuns,
  },
  {
    key: "50-career-rbi",
    title: "50 Career RBI",
    tier: "gold",
    target: 50,
    detail: "Record 50 career RBI.",
    progress: ({ career }) => career.rbi,
  },
  {
    key: "50-career-games",
    title: "50 Game Club",
    tier: "silver",
    target: 50,
    detail: "Appear in 50 NDSC games.",
    progress: ({ career }) => career.games,
  },
  {
    key: "50-career-runs",
    title: "Run Producer",
    tier: "gold",
    target: 50,
    detail: "Score 50 career runs.",
    progress: ({ career }) => career.runs,
  },
  {
    key: "75-career-hits",
    title: "Hit Machine",
    tier: "gold",
    target: 75,
    detail: "Reach 75 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "100-career-hits",
    title: "100 Career Hits",
    tier: "gold",
    target: 100,
    detail: "Reach 100 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "100-career-games",
    title: "Ever Present",
    tier: "gold",
    target: 100,
    detail: "Appear in 100 NDSC games.",
    progress: ({ career }) => career.games,
  },
  {
    key: "100-career-rbi",
    title: "RBI Century",
    tier: "gold",
    target: 100,
    detail: "Record 100 career RBI.",
    progress: ({ career }) => career.rbi,
  },
  {
    key: "100-career-runs",
    title: "Century Runner",
    tier: "gold",
    target: 100,
    detail: "Score 100 career runs.",
    progress: ({ career }) => career.runs,
  },
  {
    key: "10-home-runs",
    title: "Fence Finder",
    tier: "gold",
    target: 10,
    detail: "Hit 10 career home runs.",
    progress: ({ career }) => career.homeRuns,
  },
  {
    key: "25-home-runs",
    title: "Power Surge",
    tier: "platinum",
    target: 25,
    detail: "Hit 25 career home runs.",
    progress: ({ career }) => career.homeRuns,
  },
  {
    key: "mvp-pedigree",
    title: "MVP Pedigree",
    tier: "gold",
    target: 3,
    detail: "Win three MVP awards.",
    progress: ({ mvpAwards }) => mvpAwards,
  },
  {
    key: "award-cabinet",
    title: "Full Cabinet",
    tier: "gold",
    target: 5,
    detail: "Win five club or team awards.",
    progress: ({ awards }) => awards.length,
  },
  {
    key: "club-great",
    title: "Club Great",
    tier: "platinum",
    target: 150,
    detail: "Reach 150 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "iron-player",
    title: "Iron Player",
    tier: "platinum",
    target: 150,
    detail: "Appear in 150 NDSC games.",
    progress: ({ career }) => career.games,
  },
  {
    key: "run-factory",
    title: "Run Factory",
    tier: "platinum",
    target: 150,
    detail: "Combine for 150 career runs and RBI.",
    progress: ({ career }) => career.runs + career.rbi,
  },
  {
    key: "first-out",
    title: "First Out Recorded",
    tier: "bronze",
    target: 1,
    detail: "Record your first defensive out.",
    progress: ({ career }) => career.outs,
  },
  {
    key: "five-out-game",
    title: "Five-Out Game",
    tier: "silver",
    target: 5,
    detail: "Record five defensive outs in one game.",
    progress: ({ bestDefensiveOuts }) => bestDefensiveOuts,
  },
  {
    key: "defensive-anchor",
    title: "Defensive Anchor",
    tier: "gold",
    target: 50,
    detail: "Record 50 career defensive outs.",
    progress: ({ career }) => career.outs,
  },
  {
    key: "hundred-outs",
    title: "Hundred Outs",
    tier: "gold",
    target: 100,
    detail: "Record 100 career defensive outs.",
    progress: ({ career }) => career.outs,
  },
  {
    key: "assist-machine",
    title: "Assist Machine",
    tier: "gold",
    target: 50,
    detail: "Record 50 career assisted outs.",
    progress: ({ career }) => career.ao,
  },
  {
    key: "solo-specialist",
    title: "Solo Specialist",
    tier: "gold",
    target: 50,
    detail: "Record 50 career unassisted outs.",
    progress: ({ career }) => career.uao,
  },
  {
    key: "gold-glove-chase",
    title: "Gold Glove Chase",
    tier: "platinum",
    target: 200,
    detail: "Record 200 career defensive outs.",
    progress: ({ career }) => career.outs,
  },
  {
    key: "innings-eater",
    title: "Innings Eater",
    tier: "platinum",
    target: 500,
    detail: "Play 500 defensive innings.",
    progress: ({ career }) => career.innings,
  },
  {
    key: "ndsc-legend",
    title: "NDSC Legend",
    tier: "platinum",
    target: 200,
    detail: "200 games and 200 hits.",
    progress: ({ career }) => Math.min(career.games, career.hits),
  },
  {
    key: "200-career-hits",
    title: "200 Hit Legend",
    tier: "platinum",
    target: 200,
    detail: "Reach 200 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "250-career-games",
    title: "Club Immortal",
    tier: "platinum",
    target: 250,
    detail: "Appear in 250 NDSC games.",
    progress: ({ career }) => career.games,
  },
  {
    key: "300-hit-mountain",
    title: "300 Hit Mountain",
    tier: "platinum",
    target: 300,
    detail: "Reach 300 career hits.",
    progress: ({ career }) => career.hits,
  },
  {
    key: "ops-monster",
    title: "OPS Monster",
    tier: "platinum",
    target: 3000,
    detail: "Build a career OPS of 3.000 or better.",
    progress: ({ career }) => Math.round((career.ops ?? 0) * 1000),
  },
  {
    key: "runs-machine",
    title: "Runs Machine",
    tier: "silver",
    target: 4,
    detail: "Score four runs in a game.",
    progress: ({ bestRuns }) => bestRuns,
  },
  {
    key: "rbi-burst",
    title: "RBI Burst",
    tier: "silver",
    target: 5,
    detail: "Five RBI in a game.",
    progress: ({ bestRbi }) => bestRbi,
  },
];
